Add equations by Lucas
trixi-framework/TrixiAtmo.jl pull request #21
Opened 2024-07-19 11:36 UTC by benegee

I propose to add the moist Euler equations implemented by Lucas, as-is, as a first step. @Arpit-Babbar and @FnHck then have a common basis for their experiments.

Note that we should review, clean up, ... this at some point. But maybe we can postpone this until we start implementing alternative equations.

2024-07-19 11:53 UTC, benegee commented
# Dry air consistency check

I also added a first test, which runs Trixi.jl's `elixir_euler_warm_bubble.jl` and then runs the same elixir again using the equations defined in TrixiAtmo.jl. Thereby we can make sure that the special case of a dry atmosphere, with the additional components set to 0, yields the same results a the ordinary Euler equations in Trixi.jl.

`trixi_include` comes in handy here as it allows to overwrite the elixir an the fly. However, this can certainly be improved. See e.g. https://github.com/trixi-framework/TrixiAtmo.jl/actions/runs/10007442043/job/27662157328?pr=21#step:5:690

2024-07-19 15:09 UTC, tristanmontoya requested changes

2024-07-19 15:09 UTC, tristanmontoya commented on src/equations/compressible_moist_euler_2d_lucas.jl
> +    # Raylight damping sponge source term form A. Sridhar et al.,
```suggestion
    # Rayleigh damping sponge source term form A. Sridhar et al.,
```

2024-07-19 15:09 UTC, tristanmontoya commented on src/equations/compressible_moist_euler_2d_lucas.jl
> +    @inline function source_terms_nonhydrostatic_raylight_sponge(u, x, t,
```suggestion
    @inline function source_terms_nonhydrostatic_rayleigh_sponge(u, x, t,
```

2024-07-23 11:22 UTC, benegee commented on test/test_trixi_consistency.jl
Sorry for that! In a way this PR was not yet ready to go as I was not very confident about the double trixi_include.

The errors were due to a different parameter setting. This is now adapted and allows to further decrease the tolerances. Maybe we should think about how strict the tolerances should be. We could of course just adopt the Trixi.jl defaults.

2024-07-23 21:07 UTC, tristanmontoya approved these changes

2024-07-23 21:07 UTC, tristanmontoya approved these changes

2024-07-23 21:08 UTC, tristanmontoya approved these changes

2024-07-23 22:55 UTC, merged