WIP: Covariant formulation of the shallow water equations
trixi-framework/TrixiAtmo.jl pull request #58
Opened 2024-12-23 22:39 UTC by tristanmontoya

Re-implementing #37 with entropy-stable split forms and auxiliary variables.

2025-01-27 16:55 UTC, amrueda requested changes
Many thanks, @tristanmontoya! great work!
I have not checked the math thoroughly, but I leave a couple of comments below. 
BTW, thanks for improving the documentation of my elixirs as well!

2025-01-27 18:06 UTC, tristanmontoya commented on src/solvers/dgsem_p4est/dg_2d_manifold_in_3d_covariant.jl
> +end
Good point. I want to have a formulation that is exactly equivalent to the weak form as a baseline. This can be done using an equivalent flux-differencing form, but the nonconservative flux will return zero unless there is bottom topography. That's probably a better solution (and it won't return zero once we add the bottom topography).

2025-01-27 18:07 UTC, tristanmontoya commented on src/equations/covariant_shallow_water.jl
> +@inline function source_terms_weak_form(u, x, t, aux_vars,
That makes sense. I like the idea of splitting it, probably clearer that way.

2025-01-27 18:13 UTC, tristanmontoya commented on src/equations/covariant_shallow_water.jl
> +                                        DissipationLocalLaxFriedrichs(max_abs_speed_naive))
I am not 100% sure if it's provably entropy stable with this dissipation term, but I am also not sure about the standard LLF for this problem (we would have to do the theoretical analysis). The entropy variable jump approach would be my preference, but haven't looked into how straightforward the implementation would be. I will also look into what needs to be done to use the standard LLF here.

2025-01-28 18:51 UTC, tristanmontoya commented on src/equations/covariant_shallow_water.jl
> +                                        DissipationLocalLaxFriedrichs(max_abs_speed_naive))
The difficulty in the implementation here is that the flux-differencing approach defines the physical flux differently from the standard weak form, which makes `flux_central` ambiguous. One solution would be to make them different equations, but this is a bit annoying as it's really just two ways of writing the same equations.

2025-01-29 04:28 UTC, tristanmontoya commented on src/solvers/dgsem_p4est/dg_2d_manifold_in_3d_covariant.jl
> +end
As discussed in https://github.com/trixi-framework/TrixiAtmo.jl/pull/58#discussion_r1932698079, I have made the "standard" covariant form its own equation set separate from the (experimental for now) split formulation.

2025-01-29 11:12 UTC, amrueda commented on src/equations/covariant_shallow_water.jl
> +                                        DissipationLocalLaxFriedrichs(max_abs_speed_naive))
I agree that it is a bit annoying to have two equation sets for the same equation. However, I think that it is a good solution here because it avoids the ambiguous definition of `flux` and ensures that the two-point fluxes are consistent with `flux`... In your previous implementation that was a bit confusing. 

We can postpone the implementation of the different LLF variants for a future PR.

2025-01-29 11:14 UTC, amrueda commented on src/solvers/dgsem_p4est/dg_2d_manifold_in_3d_covariant.jl
> +end
I think that it is a good solution to have two equation sets in this case (see https://github.com/trixi-framework/TrixiAtmo.jl/pull/58#discussion_r1933690011). This solves the issue with `weak_form_kernel!` for the moment, but we will have to revisit it as soon as we add the bottom topography terms 😅 . Let's postpone that for a future PR!

2025-01-29 18:26 UTC, tristanmontoya commented
> LGTM! Thanks, @tristanmontoya! Some minor comments below:

Great, thanks for your review! Going to make those changes and merge now.

2025-01-29 19:51 UTC, merged